---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp
  namespace: webapp
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webapp
  namespace: webapp
subjects:
- kind: ServiceAccount
  name: webapp
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
