---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-trust
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager-trust
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
  interval: 10m0s
  dependsOn:
  - name: cert-manager
    namespace: cert-manager
  values:
    image:
      repository: quay.io/jetstack/cert-manager-trust
      tag: v0.2.0
    trust:
      namespace: cert-manager
