---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: api
spec:
  path: ./podinfo
  serviceAccountName: api
  targetNamespace: api
  wait: true
  prune: true
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
