---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: api
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api
  namespace: api
subjects:
- kind: ServiceAccount
  name: api
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
